# Generated by Django 5.2.16 on 2026-10-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_company_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='old_dues',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
